///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test.androidTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckElementsOnHomeScreenTest recording.
    /// </summary>
    [TestModule("13c6047b-28bc-4708-81b4-10a62c5c7c0a", ModuleType.Recording, 1)]
    public partial class CheckElementsOnHomeScreenTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test.TestRepository repository.
        /// </summary>
        public static Test.TestRepository repo = Test.TestRepository.Instance;

        static CheckElementsOnHomeScreenTest instance = new CheckElementsOnHomeScreenTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckElementsOnHomeScreenTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckElementsOnHomeScreenTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'io.selendroid.testapp' on device 'USB-00f540f2c4f126d9'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-00f540f2c4f126d9", "io.selendroid.testapp", true);
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Hello Default Locale, Selendroid-test-app!') on item 'IoSelendroidTestapp.HomeScreenActivity.HelloDefaultLocaleSelendroidTestAp'.", repo.IoSelendroidTestapp.HomeScreenActivity.HelloDefaultLocaleSelendroidTestApInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.HelloDefaultLocaleSelendroidTestApInfo, "Text", "Hello Default Locale, Selendroid-test-app!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Localization (L10n) locator test') on item 'IoSelendroidTestapp.HomeScreenActivity.LocalizationL10nLocatorTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.LocalizationL10nLocatorTestInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.LocalizationL10nLocatorTestInfo, "Text", "Localization (L10n) locator test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.HomeScreenActivity.StartUserRegistration'.", repo.IoSelendroidTestapp.HomeScreenActivity.StartUserRegistrationInfo, new RecordItemIndex(3));
            Validate.Exists(repo.IoSelendroidTestapp.HomeScreenActivity.StartUserRegistrationInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebview'.", repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebviewInfo, new RecordItemIndex(4));
            Validate.Exists(repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebviewInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'IoSelendroidTestapp.HomeScreenActivity.MyTextField'.", repo.IoSelendroidTestapp.HomeScreenActivity.MyTextFieldInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.MyTextFieldInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Show Progress Bar for a while') on item 'IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTestInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTestInfo, "Text", "Show Progress Bar for a while");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'IoSelendroidTestapp.HomeScreenActivity.InputAddsCheckBox'.", repo.IoSelendroidTestapp.HomeScreenActivity.InputAddsCheckBoxInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.InputAddsCheckBoxInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Display text view') on item 'IoSelendroidTestapp.HomeScreenActivity.VisibleButtonTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.VisibleButtonTestInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.VisibleButtonTestInfo, "Text", "Display text view");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Displays a Toast') on item 'IoSelendroidTestapp.HomeScreenActivity.ShowToastButton'.", repo.IoSelendroidTestapp.HomeScreenActivity.ShowToastButtonInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.ShowToastButtonInfo, "Text", "Displays a Toast");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Display Popup Window') on item 'IoSelendroidTestapp.HomeScreenActivity.ShowPopupWindowButton'.", repo.IoSelendroidTestapp.HomeScreenActivity.ShowPopupWindowButtonInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.ShowPopupWindowButtonInfo, "Text", "Display Popup Window");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Press to throw unhandled exception') on item 'IoSelendroidTestapp.HomeScreenActivity.ExceptionTestButton'.", repo.IoSelendroidTestapp.HomeScreenActivity.ExceptionTestButtonInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.ExceptionTestButtonInfo, "Text", "Press to throw unhandled exception");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'IoSelendroidTestapp.HomeScreenActivity.ExceptionTestField'.", repo.IoSelendroidTestapp.HomeScreenActivity.ExceptionTestFieldInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.ExceptionTestFieldInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Display and focus on layout') on item 'IoSelendroidTestapp.HomeScreenActivity.TopLevelElementTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.TopLevelElementTestInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.TopLevelElementTestInfo, "Text", "Display and focus on layout");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Touch Actions') on item 'IoSelendroidTestapp.HomeScreenActivity.TouchTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.TouchTestInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.TouchTestInfo, "Text", "Touch Actions");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
