///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test.androidTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GesturesTest recording.
    /// </summary>
    [TestModule("90376396-70b5-408b-849b-15ec60c800e3", ModuleType.Recording, 1)]
    public partial class GesturesTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test.TestRepository repository.
        /// </summary>
        public static Test.TestRepository repo = Test.TestRepository.Instance;

        static GesturesTest instance = new GesturesTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GesturesTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GesturesTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'io.selendroid.testapp' on device 'USB-00f540f2c4f126d9'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-00f540f2c4f126d9", "io.selendroid.testapp", true);
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Touch Actions') on item 'IoSelendroidTestapp.HomeScreenActivity.TouchTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.TouchTestInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.TouchTestInfo, "Text", "Touch Actions");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.HomeScreenActivity.TouchTest' at Center", repo.IoSelendroidTestapp.HomeScreenActivity.TouchTestInfo, new RecordItemIndex(2));
            repo.IoSelendroidTestapp.HomeScreenActivity.TouchTest.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Linear' at Center", repo.IoSelendroidTestapp.LinearInfo, new RecordItemIndex(3));
            repo.IoSelendroidTestapp.Linear.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Linear' at Center", repo.IoSelendroidTestapp.LinearInfo, new RecordItemIndex(4));
            repo.IoSelendroidTestapp.Linear.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SINGLE TAP CONFIRMED') on item 'IoSelendroidTestapp.TouchGesturesActivity1.SINGLETAPCONFIRMED'.", repo.IoSelendroidTestapp.TouchGesturesActivity1.SINGLETAPCONFIRMEDInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.IoSelendroidTestapp.TouchGesturesActivity1.SINGLETAPCONFIRMEDInfo, "Text", "SINGLE TAP CONFIRMED");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Touch", "DoubleTap item 'IoSelendroidTestapp.TouchGesturesActivity1.ScaleFactor10' at Center", repo.IoSelendroidTestapp.TouchGesturesActivity1.ScaleFactor10Info, new RecordItemIndex(7));
            repo.IoSelendroidTestapp.TouchGesturesActivity1.ScaleFactor10.DoubleTap();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "LongTouch item 'IoSelendroidTestapp.Linear' at Center", repo.IoSelendroidTestapp.LinearInfo, new RecordItemIndex(9));
            repo.IoSelendroidTestapp.Linear.LongTouch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='LONG PRESS') on item 'IoSelendroidTestapp.TouchGesturesActivity1.LONGPRESS'.", repo.IoSelendroidTestapp.TouchGesturesActivity1.LONGPRESSInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.IoSelendroidTestapp.TouchGesturesActivity1.LONGPRESSInfo, "Text", "LONG PRESS");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'IoSelendroidTestapp.TouchGesturesActivity'.", repo.IoSelendroidTestapp.TouchGesturesActivityInfo, new RecordItemIndex(11));
            repo.IoSelendroidTestapp.TouchGesturesActivity.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
