///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test.androidTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RegisterUserTest recording.
    /// </summary>
    [TestModule("e25a21c7-e9e0-44e4-8989-6aec383df8e5", ModuleType.Recording, 1)]
    public partial class RegisterUserTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test.TestRepository repository.
        /// </summary>
        public static Test.TestRepository repo = Test.TestRepository.Instance;

        static RegisterUserTest instance = new RegisterUserTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RegisterUserTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RegisterUserTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'io.selendroid.testapp' on device 'USB-00f540f2c4f126d9'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-00f540f2c4f126d9", "io.selendroid.testapp", true);
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Show Progress Bar for a while') on item 'IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTest'.", repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTestInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTestInfo, "Text", "Show Progress Bar for a while");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTest' at Center", repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTestInfo, new RecordItemIndex(2));
            repo.IoSelendroidTestapp.HomeScreenActivity.WaitingButtonTest.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Waiting Dialog') on item 'IoSelendroidTestapp.WaitingDialog'.", repo.IoSelendroidTestapp.WaitingDialogInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.IoSelendroidTestapp.WaitingDialogInfo, "Text", "Waiting Dialog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome to register a new User') on item 'IoSelendroidTestapp.Content.WelcomeToRegisterANewUser'.", repo.IoSelendroidTestapp.Content.WelcomeToRegisterANewUserInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.WelcomeToRegisterANewUserInfo, "Text", "Welcome to register a new User");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'IoSelendroidTestapp.Content.InputUsername'.", repo.IoSelendroidTestapp.Content.InputUsernameInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.InputUsernameInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'IoSelendroidTestapp.Content.InputEmail'.", repo.IoSelendroidTestapp.Content.InputEmailInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.InputEmailInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'IoSelendroidTestapp.Content.InputPassword'.", repo.IoSelendroidTestapp.Content.InputPasswordInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.InputPasswordInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Mr. Burns') on item 'IoSelendroidTestapp.Content.InputName'.", repo.IoSelendroidTestapp.Content.InputNameInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.InputNameInfo, "Text", "Mr. Burns");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.Content.InputPreferedProgrammingLanguage'.", repo.IoSelendroidTestapp.Content.InputPreferedProgrammingLanguageInfo, new RecordItemIndex(9));
            Validate.Exists(repo.IoSelendroidTestapp.Content.InputPreferedProgrammingLanguageInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'IoSelendroidTestapp.Content.InputAdds'.", repo.IoSelendroidTestapp.Content.InputAddsInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.InputAddsInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Register User (verify)') on item 'IoSelendroidTestapp.Content.BtnRegisterUser'.", repo.IoSelendroidTestapp.Content.BtnRegisterUserInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.IoSelendroidTestapp.Content.BtnRegisterUserInfo, "Text", "Register User (verify)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputPassword' at Center", repo.IoSelendroidTestapp.Content.InputPasswordInfo, new RecordItemIndex(12));
            repo.IoSelendroidTestapp.Content.InputPassword.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputUsername' at Center", repo.IoSelendroidTestapp.Content.InputUsernameInfo, new RecordItemIndex(13));
            repo.IoSelendroidTestapp.Content.InputUsername.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'test1' on item 'IoSelendroidTestapp.Content.InputUsername'.", repo.IoSelendroidTestapp.Content.InputUsernameInfo, new RecordItemIndex(14));
            repo.IoSelendroidTestapp.Content.InputUsername.Element.SetAttributeValue("Text", "test1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputEmail' at Center", repo.IoSelendroidTestapp.Content.InputEmailInfo, new RecordItemIndex(15));
            repo.IoSelendroidTestapp.Content.InputEmail.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'test1@gmail.com' on item 'IoSelendroidTestapp.Content.InputEmail'.", repo.IoSelendroidTestapp.Content.InputEmailInfo, new RecordItemIndex(16));
            repo.IoSelendroidTestapp.Content.InputEmail.Element.SetAttributeValue("Text", "test1@gmail.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputPassword' at Center", repo.IoSelendroidTestapp.Content.InputPasswordInfo, new RecordItemIndex(17));
            repo.IoSelendroidTestapp.Content.InputPassword.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '12345' on item 'IoSelendroidTestapp.Content.InputPassword'.", repo.IoSelendroidTestapp.Content.InputPasswordInfo, new RecordItemIndex(18));
            repo.IoSelendroidTestapp.Content.InputPassword.Element.SetAttributeValue("Text", "12345");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputName' at Center", repo.IoSelendroidTestapp.Content.InputNameInfo, new RecordItemIndex(19));
            repo.IoSelendroidTestapp.Content.InputName.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '' on item 'IoSelendroidTestapp.Content.InputName'.", repo.IoSelendroidTestapp.Content.InputNameInfo, new RecordItemIndex(20));
            repo.IoSelendroidTestapp.Content.InputName.Element.SetAttributeValue("Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'IoSelendroidTestapp.RegisterUserActivity'.", repo.IoSelendroidTestapp.RegisterUserActivityInfo, new RecordItemIndex(21));
            repo.IoSelendroidTestapp.RegisterUserActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Mary Strawberry ' on item 'IoSelendroidTestapp.Content.InputName'.", repo.IoSelendroidTestapp.Content.InputNameInfo, new RecordItemIndex(22));
            repo.IoSelendroidTestapp.Content.InputName.Element.SetAttributeValue("Text", "Mary Strawberry ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputPreferedProgrammingLanguage' at Center", repo.IoSelendroidTestapp.Content.InputPreferedProgrammingLanguageInfo, new RecordItemIndex(23));
            repo.IoSelendroidTestapp.Content.InputPreferedProgrammingLanguage.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Text1' at Center", repo.IoSelendroidTestapp.Text1Info, new RecordItemIndex(24));
            repo.IoSelendroidTestapp.Text1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.InputAdds' at Center", repo.IoSelendroidTestapp.Content.InputAddsInfo, new RecordItemIndex(25));
            repo.IoSelendroidTestapp.Content.InputAdds.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Content.BtnRegisterUser' at Center", repo.IoSelendroidTestapp.Content.BtnRegisterUserInfo, new RecordItemIndex(26));
            repo.IoSelendroidTestapp.Content.BtnRegisterUser.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.TableLayout1.TableRowName'.", repo.IoSelendroidTestapp.TableLayout1.TableRowNameInfo, new RecordItemIndex(27));
            Validate.Exists(repo.IoSelendroidTestapp.TableLayout1.TableRowNameInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Register User') on item 'IoSelendroidTestapp.ButtonRegisterUser'.", repo.IoSelendroidTestapp.ButtonRegisterUserInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.IoSelendroidTestapp.ButtonRegisterUserInfo, "Text", "Register User");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.ButtonRegisterUser' at Center", repo.IoSelendroidTestapp.ButtonRegisterUserInfo, new RecordItemIndex(29));
            repo.IoSelendroidTestapp.ButtonRegisterUser.Touch();
            Delay.Milliseconds(1000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
