///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test.androidTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WebViewTest recording.
    /// </summary>
    [TestModule("c123ed6c-718d-4fe0-a0f0-6b56c16ff850", ModuleType.Recording, 1)]
    public partial class WebViewTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test.TestRepository repository.
        /// </summary>
        public static Test.TestRepository repo = Test.TestRepository.Instance;

        static WebViewTest instance = new WebViewTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WebViewTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WebViewTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'io.selendroid.testapp' on device 'USB-00f540f2c4f126d9'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-00f540f2c4f126d9", "io.selendroid.testapp", true);
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebview'.", repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebviewInfo, new RecordItemIndex(1));
            Validate.Exists(repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebviewInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebview' at Center", repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebviewInfo, new RecordItemIndex(2));
            repo.IoSelendroidTestapp.HomeScreenActivity.ButtonStartWebview.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestData'.", repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestDataInfo, new RecordItemIndex(3));
            Validate.Exists(repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestDataInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Go to home screen') on item 'IoSelendroidTestapp.WebviewTable.GoBack'.", repo.IoSelendroidTestapp.WebviewTable.GoBackInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.GoBackInfo, "Text", "Go to home screen");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestData' at 439;76", repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestDataInfo, new RecordItemIndex(5));
            repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestData.Touch("439;76");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.FormPage' at Center", repo.IoSelendroidTestapp.FormPageInfo, new RecordItemIndex(6));
            repo.IoSelendroidTestapp.FormPage.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestData' at 221;65", repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestDataInfo, new RecordItemIndex(7));
            repo.IoSelendroidTestapp.WebviewTable.SpinnerWebdriverTestData.Touch("221;65");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.TextSayHelloDemo' at Center", repo.IoSelendroidTestapp.TextSayHelloDemoInfo, new RecordItemIndex(8));
            repo.IoSelendroidTestapp.TextSayHelloDemo.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Enter your name here!') on item 'IoSelendroidTestapp.WebviewTable.NameInput'.", repo.IoSelendroidTestapp.WebviewTable.NameInputInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.NameInputInfo, "Value", "Enter your name here!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.WebviewTable.SelectTagCar'.", repo.IoSelendroidTestapp.WebviewTable.SelectTagCarInfo, new RecordItemIndex(10));
            Validate.Exists(repo.IoSelendroidTestapp.WebviewTable.SelectTagCarInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Send me your name!') on item 'IoSelendroidTestapp.WebviewTable.Submit'.", repo.IoSelendroidTestapp.WebviewTable.SubmitInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.SubmitInfo, "Value", "Send me your name!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.NameInput' at Center", repo.IoSelendroidTestapp.WebviewTable.NameInputInfo, new RecordItemIndex(12));
            repo.IoSelendroidTestapp.WebviewTable.NameInput.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.NameInput' at Center", repo.IoSelendroidTestapp.WebviewTable.NameInputInfo, new RecordItemIndex(13));
            repo.IoSelendroidTestapp.WebviewTable.NameInput.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute value to 'Kusti' on item 'IoSelendroidTestapp.WebviewTable.NameInput'.", repo.IoSelendroidTestapp.WebviewTable.NameInputInfo, new RecordItemIndex(14));
            repo.IoSelendroidTestapp.WebviewTable.NameInput.Element.SetAttributeValue("value", "Kusti");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.SelectTagCar' at Center", repo.IoSelendroidTestapp.WebviewTable.SelectTagCarInfo, new RecordItemIndex(15));
            repo.IoSelendroidTestapp.WebviewTable.SelectTagCar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.Text11' at Center", repo.IoSelendroidTestapp.Text11Info, new RecordItemIndex(16));
            repo.IoSelendroidTestapp.Text11.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'audi' on item 'IoSelendroidTestapp.WebviewTable.SelectTagCar'.", repo.IoSelendroidTestapp.WebviewTable.SelectTagCarInfo, new RecordItemIndex(17));
            repo.IoSelendroidTestapp.WebviewTable.SelectTagCar.Element.SetAttributeValue("TagValue", "audi");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.Submit' at Center", repo.IoSelendroidTestapp.WebviewTable.SubmitInfo, new RecordItemIndex(18));
            repo.IoSelendroidTestapp.WebviewTable.Submit.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IoSelendroidTestapp.WebviewTable.Here'.", repo.IoSelendroidTestapp.WebviewTable.HereInfo, new RecordItemIndex(19));
            Validate.Exists(repo.IoSelendroidTestapp.WebviewTable.HereInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\"Kusti\"\"audi\"to start again click') on item 'IoSelendroidTestapp.WebviewTable.BodyTagKustiauditoStartAgainClick'.", repo.IoSelendroidTestapp.WebviewTable.BodyTagKustiauditoStartAgainClickInfo, new RecordItemIndex(20));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.BodyTagKustiauditoStartAgainClickInfo, "InnerText", "\"Kusti\"\"audi\"to start again click");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.SomeHrTag' at Center", repo.IoSelendroidTestapp.WebviewTable.SomeHrTagInfo, new RecordItemIndex(21));
            repo.IoSelendroidTestapp.WebviewTable.SomeHrTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.Here' at Center", repo.IoSelendroidTestapp.WebviewTable.HereInfo, new RecordItemIndex(22));
            repo.IoSelendroidTestapp.WebviewTable.Here.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Send me your name!') on item 'IoSelendroidTestapp.WebviewTable.Submit'.", repo.IoSelendroidTestapp.WebviewTable.SubmitInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.SubmitInfo, "Value", "Send me your name!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Go to home screen') on item 'IoSelendroidTestapp.WebviewTable.GoBack'.", repo.IoSelendroidTestapp.WebviewTable.GoBackInfo, new RecordItemIndex(24));
            Validate.Attribute(repo.IoSelendroidTestapp.WebviewTable.GoBackInfo, "Text", "Go to home screen");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'IoSelendroidTestapp.WebviewTable.GoBack' at Center", repo.IoSelendroidTestapp.WebviewTable.GoBackInfo, new RecordItemIndex(25));
            repo.IoSelendroidTestapp.WebviewTable.GoBack.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
